export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const RESET_SERVICE_FIELD = 'RESET_SERVICE_FIELD';
export const SELECT_SERVICE = 'SELECT_SERVICE';
